=== Mingan/VSE-4IZ210-XML/regularni_vyrazy/metadata-result.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="extractedinfo">

        <xs:complexType>

            <xs:sequence maxOccurs="unbounded">
                <xs:element name="infotype">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="hit">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="value" type="xs:string"/>
                                        <xs:element name="details" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="part" maxOccurs="unbounded">
                                                  <xs:complexType>
                                                  <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="name" type="xs:string"/>
                                                  </xs:extension>
                                                  </xs:simpleContent>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="context" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


</xs:schema>

=== Mingan/VSE-4IZ210-XML/regularni_vyrazy/metadata_ttklavesnice.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href = "metadata-result_style.xsl" type = "text/xsl"?><extractedinfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="metadata-result.xsd">
    <infotype name="IČO"/>
    <infotype name="Osoba s akademickým titulem"/>
    <infotype name="NACE">
        <hit>
            <value>273300</value>
            <context> Seznam cinností podle NACE:&#xD; 273300:&#xD; Výroba elektroinstalacních zarízení&#xD; 221000:&#xD; Výroba prytových výrobku&#xD; 222000:&#xD; Výroba plastových výrobku&#xD; 26</context>
        </hit>
        <hit>
            <value>268000</value>
            <context>tronických soucástek a desek&#xD; 268000:&#xD; Výroba magnetických a optických médií&#xD; 279000:&#xD; Výroba ostatních elektrických zarízení&#xD; 461000:&#xD; Zprostredková</context>
        </hit>
        <hit>
            <value>740000</value>
            <context>u a velkoobchod v zastoupení&#xD; 740000:&#xD; Ostatní profesní, vedecké a technické cinnosti&#xD; 2 Nabízené produkty a služby&#xD; ? Fóliové štítky&#xD; (HS 3919 - Des</context>
        </hit>
    </infotype>
    <infotype name="Adresa">
        <hit>
            <value>Hruškový Dvory, 56, 586 01, Jihlava, Ceská republika</value>
            <details>
                <part name="Ulice">Hruškový Dvory</part>
                <part name="Číslo domu">56</part>
                <part name="PSČ">586 01</part>
                <part name="Město">Jihlava</part>
                <part name="Stát">Ceská republika</part>
            </details>
            <context>arku Tesla Jihlava na adrese: Hruškový Dvory 56, 586 01 Jihlava, Ceská republika.&#xD; 3.3 Obchodní sít&#xD; TT Kláves</context>
        </hit>
        <hit>
            <value>Znojemska, 94, 586 01, Jihlava, Ceská republika</value>
            <details>
                <part name="Ulice">Znojemska</part>
                <part name="Číslo domu">94</part>
                <part name="PSČ">586 01</part>
                <part name="Město">Jihlava</part>
                <part name="Stát">Ceská republika</part>
            </details>
            <context>ráce srovnatelné síly. Sídlo: Znojemska 94, 586 01 Jihlava&#xD; Ceská republika&#xD; Hlavní produkt: Fóliové kláv</context>
        </hit>
        <hit>
            <value>Musilova, 36, 586 01, Jihlava, Ceská republika</value>
            <details>
                <part name="Ulice">Musilova</part>
                <part name="Číslo domu">36</part>
                <part name="PSČ">586 01</part>
                <part name="Město">Jihlava</part>
                <part name="Stát">Ceská republika</part>
            </details>
            <context>ování menších zakázek. Sídlo: Musilova 36, 586 01 Jihlava&#xD; Ceská republika&#xD; Hlavní produkt: Fóliové kláv</context>
        </hit>
        <hit>
            <value>Praha, 9, 193 00, Horní Pocernice, Hlavní produkt</value>
            <details>
                <part name="Ulice">Praha</part>
                <part name="Číslo domu">9</part>
                <part name="PSČ">193 00</part>
                <part name="Město">Horní Pocernice</part>
                <part name="Stát">Hlavní produkt</part>
            </details>
            <context>ozbu. Sídlo: Hrdonovická 178&#xD; Praha 9&#xD; 193 00 Horní Pocernice&#xD; Hlavní produkt: Zdroje&#xD; Transformátory&#xD; Merí</context>
        </hit>
        <hit>
            <value>Borsigstraße, 17-25, 32257, Bünde, Germany</value>
            <details>
                <part name="Ulice">Borsigstraße</part>
                <part name="Číslo domu">17-25</part>
                <part name="PSČ">32257</part>
                <part name="Město">Bünde</part>
                <part name="Stát">Germany</part>
            </details>
            <context>ším na evropském trhu. Sídlo: Borsigstraße 17-25&#xD; 32257 Bünde,&#xD; Germany&#xD; Hlavní produkt: Pouzdra pro </context>
        </hit>
    </infotype>
    <infotype name="HS">
        <hit>
            <value>HS 3919</value>
            <context> a služby&#xD; ? Fóliové štítky&#xD; (HS 3919 - Desky folie filmy ap samole</context>
        </hit>
        <hit>
            <value>HS 847160</value>
            <context> fólie&#xD; - 3 -&#xD; ? Klávesnice&#xD; (HS 847160 - Jednotky vstupní nebo výstu</context>
        </hit>
    </infotype>
    <infotype name="ISO norma">
        <hit>
            <value>ISO 9001:2008</value>
            <context>a kvalite jejich produktu.&#xD; ? ISO 9001:2008 - zavedla a poutívá systém ma</context>
        </hit>
        <hit>
            <value>ISO 14001:2005</value>
            <context> všeobecné poutití.&#xD; ? CSN EN ISO 14001:2005 - zavedla a poutívá systém en</context>
        </hit>
    </infotype>
    <infotype name="Telefon">
        <hit>
            <value>+420 602 133 210</value>
            <context> technického oddelení&#xD; Mob..: +420 602 133 210</context>
        </hit>
        <hit>
            <value>+420 567 113 525</value>
            <context>&#xD; Tel..: +420 567 113 525</context>
        </hit>
        <hit>
            <value>+420 567 113 522</value>
            <context>&#xD; Fax: +420 567 113 522</context>
        </hit>
        <hit>
            <value>+420 602 133 220</value>
            <context>í obchodního oddelení&#xD; Mob..: +420 602 133 220</context>
        </hit>
        <hit>
            <value>+420 567 113 522</value>
            <context>&#xD; Tel..: +420 567 113 522</context>
        </hit>
        <hit>
            <value>+420 567 113 522</value>
            <context>&#xD; Fax: +420 567 113 522</context>
        </hit>
    </infotype>
</extractedinfo>
